// <auto-generated />
using System;
using GymManagmentSystem.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagmentSystem.Migrations
{
    [DbContext(typeof(GymDb))]
    [Migration("20251120124542_seedingData")]
    partial class seedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagmentSystem.DataBase.MemberMembership", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId", "MembershipId");

                    b.HasIndex("MembershipId");

                    b.ToTable("MemberMemberships");

                    b.HasData(
                        new
                        {
                            MemberId = "member-1",
                            MembershipId = 1,
                            EndDate = new DateTime(2025, 12, 20, 12, 45, 40, 862, DateTimeKind.Utc).AddTicks(9216),
                            IsActive = true,
                            StartDate = new DateTime(2025, 11, 20, 12, 45, 40, 862, DateTimeKind.Utc).AddTicks(9208)
                        });
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationInDays = 30,
                            Name = "Basic",
                            Price = 20m
                        },
                        new
                        {
                            Id = 2,
                            DurationInDays = 90,
                            Name = "Standard",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3,
                            DurationInDays = 365,
                            Name = "Premium",
                            Price = 150m
                        });
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MemberId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NextRenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId1");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = "user-admin-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0706dde9-b5d0-4e5c-b41e-1a358205b6fd",
                            Email = "admin@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GYM.COM",
                            NormalizedUserName = "ADMIN@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFvx1hbDklkGCPVoTw9wDOxgUdaTunvJUKJ4E1n94G6qjSNAoYsE3RofvxP6cf6+7g==",
                            PhoneNumberConfirmed = false,
                            SecName = "Admin",
                            SecurityStamp = "b9be71aa-eae6-4b17-b807-ab0b789041f2",
                            TwoFactorEnabled = false,
                            UserName = "admin@gym.com"
                        });
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.WorkOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkOutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkOutPlanId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.WorkOutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("MemberId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("TrainerId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId1");

                    b.HasIndex("TrainerId1");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-trainer",
                            Name = "Trainer",
                            NormalizedName = "TRAINER"
                        },
                        new
                        {
                            Id = "role-member",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "trainer-1",
                            RoleId = "role-trainer"
                        },
                        new
                        {
                            UserId = "member-1",
                            RoleId = "role-member"
                        },
                        new
                        {
                            UserId = "user-admin-1",
                            RoleId = "role-admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.Member", b =>
                {
                    b.HasBaseType("GymManagmentSystem.DataBase.User");

                    b.HasDiscriminator().HasValue("Member");

                    b.HasData(
                        new
                        {
                            Id = "member-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7820284-7c12-4f5e-ba29-3a009d7c30ee",
                            Email = "member1@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Mohamed",
                            LockoutEnabled = false,
                            NormalizedEmail = "MEMBER1@GYM.COM",
                            NormalizedUserName = "MEMBER1@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENQef26N56Zmd78XgaK6cezeI4jNxhiEIU5tdV1C2OHlapzDX4MKa1/zzfv3r2H9pA==",
                            PhoneNumberConfirmed = false,
                            SecName = "Ibrahim",
                            SecurityStamp = "8f15e65f-9fe1-41ad-ab08-ff608cc1f508",
                            TwoFactorEnabled = false,
                            UserName = "member1@gym.com"
                        });
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.Trainer", b =>
                {
                    b.HasBaseType("GymManagmentSystem.DataBase.User");

                    b.HasDiscriminator().HasValue("Trainer");

                    b.HasData(
                        new
                        {
                            Id = "trainer-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02e53003-c5e3-43e1-9885-a741f3fe7838",
                            Email = "trainer1@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Mohamed",
                            LockoutEnabled = false,
                            NormalizedEmail = "TRAINER1@GYM.COM",
                            NormalizedUserName = "TRAINER1@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC4C8iYL7i1r+Fa9h176DQBSv9YHKx7KDndgyZyUXUHKSYFupmufEn/v1v6we2VYdg==",
                            PhoneNumberConfirmed = false,
                            SecName = "Mohsen",
                            SecurityStamp = "5a25f05f-94ab-4e4f-a917-f967e3cf44af",
                            TwoFactorEnabled = false,
                            UserName = "trainer1@gym.com"
                        });
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.MemberMembership", b =>
                {
                    b.HasOne("GymManagmentSystem.DataBase.Member", "Member")
                        .WithMany("MemberMemberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagmentSystem.DataBase.Membership", "Membership")
                        .WithMany("MemberMemberships")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.Payment", b =>
                {
                    b.HasOne("GymManagmentSystem.DataBase.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId1");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.WorkOut", b =>
                {
                    b.HasOne("GymManagmentSystem.DataBase.WorkOutPlan", "WorkOutPlan")
                        .WithMany("Workouts")
                        .HasForeignKey("WorkOutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOutPlan");
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.WorkOutPlan", b =>
                {
                    b.HasOne("GymManagmentSystem.DataBase.Member", "Member")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("MemberId1");

                    b.HasOne("GymManagmentSystem.DataBase.Trainer", "Trainer")
                        .WithMany("WorkOutPlans")
                        .HasForeignKey("TrainerId1");

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GymManagmentSystem.DataBase.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GymManagmentSystem.DataBase.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagmentSystem.DataBase.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GymManagmentSystem.DataBase.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.Membership", b =>
                {
                    b.Navigation("MemberMemberships");
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.WorkOutPlan", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.Member", b =>
                {
                    b.Navigation("MemberMemberships");

                    b.Navigation("Payments");

                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("GymManagmentSystem.DataBase.Trainer", b =>
                {
                    b.Navigation("WorkOutPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
